const crypto = require('crypto');

const sessions = new Map();
const cookieName = 'leetclass_session';
function configured() { return Boolean(process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET && process.env.GOOGLE_CALLBACK_URL); }
function parseCookies(req) { return Object.fromEntries((req.headers.cookie || '').split(';').map(x => x.trim().split('=').map(decodeURIComponent)).filter(x => x.length === 2)); }
function currentUser(req) { const id = parseCookies(req)[cookieName]; return id ? sessions.get(id)?.user || null : null; }
function setSession(res, user) { const token = crypto.randomBytes(32).toString('hex'); sessions.set(token, { user, createdAt: Date.now() }); const secure = process.env.SESSION_COOKIE_SECURE === 'true' ? '; Secure' : ''; res.setHeader('Set-Cookie', `${cookieName}=${token}; HttpOnly; SameSite=Lax; Path=/${secure}`); }
function clearSession(req, res) { const id = parseCookies(req)[cookieName]; if (id) sessions.delete(id); res.setHeader('Set-Cookie', `${cookieName}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`); }
function beginGoogle(res) { if (!configured()) throw new Error('Google OAuth is not configured. Add the variables in .env before signing in.'); const state = crypto.randomBytes(20).toString('hex'); sessions.set(`state:${state}`, { createdAt: Date.now() }); const params = new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID, redirect_uri: process.env.GOOGLE_CALLBACK_URL, response_type: 'code', scope: 'openid email profile', state, prompt: 'select_account' }); res.writeHead(302, { location: `https://accounts.google.com/o/oauth2/v2/auth?${params}` }); res.end(); }
async function finishGoogle(url, req, res) { const code = url.searchParams.get('code'); const state = url.searchParams.get('state'); if (!code || !sessions.has(`state:${state}`)) throw new Error('Your sign-in session expired. Please try again.'); sessions.delete(`state:${state}`); const tokenResponse = await fetch('https://oauth2.googleapis.com/token', { method:'POST', headers:{'content-type':'application/x-www-form-urlencoded'}, body:new URLSearchParams({ code, client_id:process.env.GOOGLE_CLIENT_ID, client_secret:process.env.GOOGLE_CLIENT_SECRET, redirect_uri:process.env.GOOGLE_CALLBACK_URL, grant_type:'authorization_code' }) }); if (!tokenResponse.ok) throw new Error('Google could not complete sign-in. Please try again.'); const tokens = await tokenResponse.json(); const profileResponse = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', { headers:{ authorization:`Bearer ${tokens.access_token}` } }); if (!profileResponse.ok) throw new Error('Google profile information is unavailable.'); const profile = await profileResponse.json(); setSession(res, { id:profile.sub, name:profile.name || profile.email, email:profile.email, picture:profile.picture || '' }); res.writeHead(302, { location:'/' }); res.end(); }
module.exports = { configured, currentUser, setSession, clearSession, beginGoogle, finishGoogle };
